
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
 import java.sql.PreparedStatement; 


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acara
 */
public class createa_account extends javax.swing.JFrame {


    public createa_account() {
        initComponents();
        // Veritabanı bilgileri
    }
    
    public void close() {
    WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 800));
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setPreferredSize(new java.awt.Dimension(1280, 800));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(password);
        password.setBounds(280, 490, 270, 50);
        getContentPane().add(username);
        username.setBounds(280, 410, 270, 50);

        jButton1.setActionCommand("create_account");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 580, 260, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/create_account.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1290, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static int totalaccounts = 2;
    private void create_account(){
            String username1 = username.getText();
            String password1 = password.getText();
            try {                 
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");         
                String path= "C:\\Users\\acara\\Documents\\NetBeansProjects\\whopays\\src\\whopays.accdb";  
                String ur = "jdbc:ucanaccess://"+path;  
                Connection con = DriverManager.getConnection(ur);                 
                try {                     
                    Statement st = con.createStatement();                     
                    ResultSet rs = st.executeQuery("SELECT * FROM userTable");
                    String query = "INSERT INTO userTable (username, password) VALUES (?, ?)";

                    // Hazırlanan ifadeyi veritabanına gönderme
                    PreparedStatement pstmt = con.prepareStatement(query);
                    pstmt.setString(1, username1); // username
                    pstmt.setString(2, password1); // password
                    pstmt.executeUpdate();
                    totalaccounts ++;
                    con.close();

                    while(rs.next()){                         
                        System.out.print(rs.getString(1));       
                        System.out.println(" "+rs.getString(2));} 
                }
                catch(Exception ex){                    
                    System.out.println("error occured "+ex);                   
                } 
                }
                catch(Exception x){                    
                    System.out.println("error occured"+x);             
                }       
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        create_account();
        close();
        login a = new login();
        a.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createa_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createa_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createa_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createa_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createa_account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
