/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acara
 */
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement; 
import java.sql.ResultSet;
 import java.sql.SQLException;
public class whopays extends javax.swing.JFrame {
    public static int toggle = 0;
    /**
     * Creates new form whopays
     */
    public void showlist(){
    ExpenseList.setText(null);
                try {
            Connection conn = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\acara\\Documents\\NetBeansProjects\\whopays\\src\\whoPays.accdb");
            Statement stmt = conn.createStatement();
    
    // expenseTable ve userTable tablolarından verileri sorgula
    String sql = "SELECT userTable.username, expenseTable.item, expenseTable.price "
                 + "FROM userTable INNER JOIN expenseTable "
                 + "ON userTable.userId = expenseTable.userId "
                 + "ORDER BY userTable.username ASC";
    ResultSet rs = stmt.executeQuery(sql);

    // JTextArea'ya verileri yazdır
    while (rs.next()) {
        String username = rs.getString("username");
        String item = rs.getString("item");
        double price = rs.getDouble("price");

        String text = username + " - " + item + " - " + price + "$" + "\n";
        ExpenseList.append(text);
    }

    rs.close();
    stmt.close();
    conn.close();
} 
                catch (SQLException e) {
    e.printStackTrace();
}
    
    }
    static double totalexpense = 0.0;
    static double eachpays = 0.0;
    public void calculate(){
    try {
        Connection conn = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\acara\\Documents\\NetBeansProjects\\whopays\\src\\whoPays.accdb");
        Statement stmt = conn.createStatement();
    
        // expenseTable ve userTable tablolarından verileri sorgula
        String sql = "SELECT userTable.username, expenseTable.price "
                 + "FROM userTable INNER JOIN expenseTable "
                 + "ON userTable.userId = expenseTable.userId ";
                
        ResultSet rs = stmt.executeQuery(sql);
        while (rs.next()){
        }
        // Toplam hesabi
        while (rs.next()) {
            double price = rs.getDouble("price");
            totalexpense = totalexpense + price;
        }
    eachpays = totalexpense / createa_account.totalaccounts;
    totalexpense = 0.0;
        System.out.println(eachpays);
        
    rs.close();
    stmt.close();
    conn.close();
    } 
                catch (SQLException e) {
    e.printStackTrace();
}
    }
    public whopays() {
        initComponents();
        ExpenseList.setVisible(true);
        showlist();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Item = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        coverthelist = new javax.swing.JLabel();
        ExpenseListjScrollPane = new javax.swing.JScrollPane();
        ExpenseList = new javax.swing.JTextArea();
        resetexpense = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        calculatebutton = new javax.swing.JButton();
        expenselist = new javax.swing.JButton();
        addexpense = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 800));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Item.setText("Enter Item");
        Item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemMouseClicked(evt);
            }
        });
        Item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemActionPerformed(evt);
            }
        });
        getContentPane().add(Item, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 280, 50));

        Price.setText("Enter Price in number");
        Price.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PriceMouseClicked(evt);
            }
        });
        Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceActionPerformed(evt);
            }
        });
        getContentPane().add(Price, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 280, 50));

        coverthelist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main.png"))); // NOI18N
        coverthelist.setText("jLabel1");
        getContentPane().add(coverthelist, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        ExpenseList.setColumns(20);
        ExpenseList.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        ExpenseList.setRows(5);
        ExpenseList.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(0, 0, 0)));
        ExpenseList.setOpaque(false);
        ExpenseListjScrollPane.setViewportView(ExpenseList);

        getContentPane().add(ExpenseListjScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 380, 520));

        resetexpense.setText("Reset Expense History");
        resetexpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetexpenseActionPerformed(evt);
            }
        });
        getContentPane().add(resetexpense, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 720, 160, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/main.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        calculatebutton.setText("jButton3");
        calculatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(calculatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 650, 100, 130));

        expenselist.setText("a");
        expenselist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenselistActionPerformed(evt);
            }
        });
        getContentPane().add(expenselist, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 700, 300, 70));

        addexpense.setText("jButton1");
        addexpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addexpenseActionPerformed(evt);
            }
        });
        getContentPane().add(addexpense, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 630, 300, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void expenselistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenselistActionPerformed
        if(toggle%2==0){
            coverthelist.setVisible(false);
            toggle++;
            showlist();
        }
        else if (toggle%2==1){
            coverthelist.setVisible(true);
            toggle++;
        }
        
 
// TODO add your handling code here:
    }//GEN-LAST:event_expenselistActionPerformed

    private void calculatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatebuttonActionPerformed
        // TODO add your handling code here:
        calculate();

    }//GEN-LAST:event_calculatebuttonActionPerformed

    private void addexpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addexpenseActionPerformed
        // TODO adyour handling code here: add expense
        String ItemInput = Item.getText();
        String PriceInput = Price.getText();
        double PriceInput1 = Double.parseDouble(PriceInput);
                try {                 
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");         
                String path= "C:\\Users\\acara\\Documents\\NetBeansProjects\\whopays\\src\\whopays.accdb";  
                String ur = "jdbc:ucanaccess://"+path;  
                Connection con = DriverManager.getConnection(ur);                 
                try {                     
                    Statement st = con.createStatement();                     
                    ResultSet rs = st.executeQuery("SELECT * FROM userTable");
                    String query = "INSERT INTO expenseTable (item, price, userId) VALUES (?, ?, ?)";

                    // Hazırlanan ifadeyi veritabanına gönderme
                    PreparedStatement pstmt = con.prepareStatement(query);
                    pstmt.setString(1, ItemInput); // item
                    pstmt.setDouble(2, PriceInput1); // price
                    pstmt.setInt(3, login.userId); //userId
                    pstmt.executeUpdate();
                    con.close();
                       
             
                    while(rs.next()){                         
                        System.out.print(rs.getString(1));       
                        System.out.println(" "+rs.getString(2));} 
                }
                catch(Exception ex){                    
                    System.out.println("error occured "+ex);                   
                } 
                }
                catch(Exception x){                    
                    System.out.println("error occured"+x);             
                }
        
        
    }//GEN-LAST:event_addexpenseActionPerformed

    private void ItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemActionPerformed
        // TODO add your handling code here:
        Item.setText(null);
    }//GEN-LAST:event_ItemActionPerformed

    private void PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceActionPerformed
        // TODO add your handling code here:
        Price.setText(null);
    }//GEN-LAST:event_PriceActionPerformed

    private void resetexpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetexpenseActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
Statement stmt = null;

try {
    // Veritabanı bağlantısını aç
    conn = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\acara\\Documents\\NetBeansProjects\\whopays\\src\\whoPays.accdb");

    // Sorguyu hazırla ve çalıştır
    String query = "DELETE FROM expenseTable;";
    stmt = conn.createStatement();
    stmt.executeUpdate(query);

    System.out.println("expenseTable tablosu başarıyla silindi.");
} catch (SQLException e) {
    System.out.println("Hata: " + e.getMessage());
} finally {
    try {
        // Bağlantıyı kapat
        if (stmt != null) {
            stmt.close();
        }
        if (conn != null) {
            conn.close();
        }
    } catch (SQLException ex) {
        System.out.println("Hata: " + ex.getMessage());
    }
}

    }//GEN-LAST:event_resetexpenseActionPerformed

    private void ItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemMouseClicked
        // TODO add your handling code here:
        Item.setText(null);
    }//GEN-LAST:event_ItemMouseClicked

    private void PriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PriceMouseClicked
        // TODO add your handling code here:
        Price.setText(null);
    }//GEN-LAST:event_PriceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(whopays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(whopays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(whopays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(whopays.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new whopays().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ExpenseList;
    private javax.swing.JScrollPane ExpenseListjScrollPane;
    private javax.swing.JTextField Item;
    private javax.swing.JTextField Price;
    private javax.swing.JButton addexpense;
    private javax.swing.JButton calculatebutton;
    private javax.swing.JLabel coverthelist;
    private javax.swing.JButton expenselist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton resetexpense;
    // End of variables declaration//GEN-END:variables
}
